# Generated by Django 4.2.1 on 2023-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Movie Name')),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('likes', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('prod_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
